version: '2'

services:
  app:
    image: 'mytests-docker:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=mytest
      - SPRING_DATASOURCE_PASSWORD=mypass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    expose:
      - 8080
    ports:
      - 8080:8080

  db:
    image: 'postgres:13.2-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=mytest
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=testdb